name: Tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [2.5, 2.6, 2.7, '3.0']
        faraday-version: ["0.9.2", "1.0"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install gems
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
      env:
        FARADAY_VERSION: ${{ matrix.faraday-version }}
